name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
env:
  FIREBASE_CLI_PREVIEWS: hostingchannels
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN  }}'
          channelId: live
          projectId: pro-profile
        
